### ISSUE TITLE
Техническое Задание

### ISSUE THREAD

**Issue by 6y6lan** [SpaiderViruS/AutoPartsStore#11]

**Comment by 6y6lan** [comment]
[Техническое задание.docx](https://github.com/SpaiderViruS/AutoPartsStore/files/9674350/default.docx)

**Comment by SpaiderViruS** [comment]
[TZ.docx](https://github.com/SpaiderViruS/AutoPartsStore/files/9823349/TZ.docx)

**Comment by SpaiderViruS** [comment]
[TZ.docx](https://github.com/SpaiderViruS/AutoPartsStore/files/9828952/TZ.docx)

**Comment by SpaiderViruS** [comment]
[TZ.docx](https://github.com/SpaiderViruS/AutoPartsStore/files/9829073/TZ.docx)
